"""Leaf: the only server-side copy — export labels in Russian and Ukrainian.

Everything the live UI shows is localized on the client. Exported files are
read outside LifeOS, so their headings and vocabulary are rendered here. No
label states a cause, judges a purchase or scores anything.
"""

RU: dict[str, str] = {
    "title": "Обзор системы",
    "revision": "ревизия",
    "status.draft": "черновик",
    "status.finalized": "завершён",
    "kind.month": "месяц",
    "kind.year": "год",
    "meta.period": "Период",
    "meta.kind": "Тип",
    "meta.revision": "Ревизия",
    "meta.status": "Статус",
    "meta.saved": "Сохранено",
    "meta.finalized": "Завершено",
    "meta.as_of": "Свидетельства на момент",
    "meta.timezone": "Часовой пояс",
    "meta.redacted": "Часть источников удалена",
    "notice": (
        "Это не вердикт и не оценка. Общего балла нет и не будет: разные единицы не "
        "складываются. Связи — ассоциации или гипотезы, не доказанные причины. Проекции "
        "верны только при указанных допущениях."
    ),
    "section.summary": "Сводка",
    "section.changed": "Что менялось",
    "section.improved": "Что улучшилось (там, где «лучше» задано вами)",
    "section.repeated": "Что повторилось",
    "section.tradeoffs": "Компромиссы и противоречия",
    "section.consequences": "Последствия (проекции при допущениях)",
    "section.position": "Финансовый контекст (введён вами)",
    "section.priorities": "Явные приоритеты в напряжении",
    "section.self_check": "Самопроверка LifeOS (не клинический тест)",
    "section.relations": "Связи",
    "section.user": "Ваши выводы и решения",
    "section.provenance": "Происхождение данных",
    "col.section": "Раздел",
    "col.items": "Пунктов",
    "col.what": "Что",
    "col.subject": "Субъект",
    "col.current": "Текущее",
    "col.reference": "Сравнение",
    "col.delta": "Разница",
    "col.desire": "Желательность",
    "col.basis": "Основание",
    "col.source": "Источник",
    "col.windows": "Периоды",
    "col.a": "Сторона А",
    "col.b": "Сторона Б",
    "col.causality": "Причинность",
    "col.impact": "Последствие",
    "col.state": "Состояние",
    "col.inputs": "Входные данные",
    "col.assumptions": "Допущения",
    "col.calculation": "Расчёт",
    "col.result": "Результат",
    "col.missing": "Не хватает",
    "col.limitations": "Ограничения",
    "col.from": "От",
    "col.type": "Тип связи",
    "col.to": "К",
    "col.epistemic": "Характер",
    "col.status": "Статус",
    "col.note": "Заметка",
    "col.period": "Период",
    "col.field": "Поле",
    "col.value": "Значение",
    "col.ordinal": "№",
    "col.table": "Таблица",
    "col.id": "Идентификатор",
    "col.question": "Вопрос",
    "col.answer": "Ответ",
    "redacted": "источник удалён",
    "none": "—",
    "unknown": "неизвестно",
    "not_checked": "не проверялась",
    "empty": "Нечего показать за период.",
    "user.reflection": "Что это значит для меня",
    "user.no_conclusion": "Вывода нет — оставлено как наблюдение",
    "user.decisions": "Что я решаю",
    "user.adjustments": "Что я решаю поменять",
    "user.nothing": "Ничего не выбрано — это нормальный итог.",
    "desire.neutral": "нейтрально",
    "desire.favorable": "в сторону вашей цели",
    "desire.unfavorable": "против вашей цели",
    "desire.unknown": "неизвестно",
    "epistemic.association": "ассоциация",
    "epistemic.hypothesis": "гипотеза",
    "source.user": "вы",
    "source.rule": "правило LifeOS",
    "source.ai": "модель",
    "rstatus.proposed": "предложено",
    "rstatus.approved": "подтверждено вами",
    "rstatus.rejected": "не связано",
    "rstatus.unsure": "не уверены",
    "state.computed": "рассчитано",
    "state.needs_input": "нужен ввод",
    "state.not_applicable": "неприменимо",
    "self_check.flag": "Возможно, есть повторяющееся затруднение с погашением, которое стоит "
    "рассмотреть.",
    "self_check.no_flag": "Условие для отметки не выполнено.",
    "self_check.rule": "Правило: отметка при 2 и более индикаторах из 7.",
}

UK: dict[str, str] = {
    **RU,
    "title": "Огляд системи",
    "revision": "ревізія",
    "status.draft": "чернетка",
    "status.finalized": "завершено",
    "kind.month": "місяць",
    "kind.year": "рік",
    "meta.period": "Період",
    "meta.kind": "Тип",
    "meta.revision": "Ревізія",
    "meta.saved": "Збережено",
    "meta.finalized": "Завершено",
    "meta.as_of": "Свідчення на момент",
    "meta.timezone": "Часовий пояс",
    "meta.redacted": "Частину джерел видалено",
    "notice": (
        "Це не вердикт і не оцінка. Загального балу немає і не буде: різні одиниці не "
        "додаються. Зв'язки — асоціації або гіпотези, а не доведені причини. Проєкції "
        "правильні лише за вказаних припущень."
    ),
    "section.summary": "Зведення",
    "section.changed": "Що змінювалося",
    "section.improved": "Що покращилося (там, де «краще» задано вами)",
    "section.repeated": "Що повторилося",
    "section.tradeoffs": "Компроміси й суперечності",
    "section.consequences": "Наслідки (проєкції за припущень)",
    "section.position": "Фінансовий контекст (введений вами)",
    "section.priorities": "Явні пріоритети в напрузі",
    "section.self_check": "Самоперевірка LifeOS (не клінічний тест)",
    "section.relations": "Зв'язки",
    "section.user": "Ваші висновки й рішення",
    "section.provenance": "Походження даних",
    "col.section": "Розділ",
    "col.items": "Пунктів",
    "col.what": "Що",
    "col.subject": "Суб'єкт",
    "col.current": "Поточне",
    "col.reference": "Порівняння",
    "col.delta": "Різниця",
    "col.desire": "Бажаність",
    "col.basis": "Підстава",
    "col.source": "Джерело",
    "col.windows": "Періоди",
    "col.a": "Сторона А",
    "col.b": "Сторона Б",
    "col.causality": "Причинність",
    "col.impact": "Наслідок",
    "col.state": "Стан",
    "col.inputs": "Вхідні дані",
    "col.assumptions": "Припущення",
    "col.calculation": "Розрахунок",
    "col.result": "Результат",
    "col.missing": "Бракує",
    "col.limitations": "Обмеження",
    "col.from": "Від",
    "col.type": "Тип зв'язку",
    "col.to": "До",
    "col.epistemic": "Характер",
    "col.status": "Статус",
    "col.note": "Нотатка",
    "col.period": "Період",
    "col.field": "Поле",
    "col.value": "Значення",
    "col.table": "Таблиця",
    "col.id": "Ідентифікатор",
    "col.question": "Питання",
    "col.answer": "Відповідь",
    "redacted": "джерело видалено",
    "unknown": "невідомо",
    "not_checked": "не перевірялася",
    "empty": "Немає що показати за період.",
    "user.reflection": "Що це означає для мене",
    "user.no_conclusion": "Висновку немає — залишено як спостереження",
    "user.decisions": "Що я вирішую",
    "user.adjustments": "Що я вирішую змінити",
    "user.nothing": "Нічого не вибрано — це нормальний підсумок.",
    "desire.neutral": "нейтрально",
    "desire.favorable": "у бік вашої цілі",
    "desire.unfavorable": "проти вашої цілі",
    "desire.unknown": "невідомо",
    "epistemic.association": "асоціація",
    "epistemic.hypothesis": "гіпотеза",
    "source.user": "ви",
    "source.rule": "правило LifeOS",
    "source.ai": "модель",
    "rstatus.proposed": "запропоновано",
    "rstatus.approved": "підтверджено вами",
    "rstatus.rejected": "не пов'язано",
    "rstatus.unsure": "не впевнені",
    "state.computed": "розраховано",
    "state.needs_input": "потрібне введення",
    "state.not_applicable": "незастосовно",
    "self_check.flag": "Можливо, є повторюване утруднення з погашенням, яке варто розглянути.",
    "self_check.no_flag": "Умову для позначки не виконано.",
    "self_check.rule": "Правило: позначка за 2 і більше індикаторів із 7.",
}

MONTHS = {
    "ru": ["январь", "февраль", "март", "апрель", "май", "июнь", "июль", "август",
           "сентябрь", "октябрь", "ноябрь", "декабрь"],
    "uk": ["січень", "лютий", "березень", "квітень", "травень", "червень", "липень",
           "серпень", "вересень", "жовтень", "листопад", "грудень"],
}

# Vocabulary rendered verbatim in exports (codes stay machine-readable in JSON).
TERMS = {
    "ru": {
        "finance_spend_vs_expectation": "Расход месяца и ожидание",
        "finance_spend_vs_prior": "Расход месяца и прошлый месяц",
        "finance_expectation_revisions": "Пересмотры ожидания",
        "finance_target_state": "Расход месяца и цель",
        "project_forecast_revisions": "Пересмотры прогноза проекта",
        "project_completion": "Завершение проекта",
        "experiment_lifecycle": "Эксперимент",
        "observation": "Наблюдение",
        "budget_deviation": "Отклонение от бюджета",
        "repeat_scenario": "Если повторится",
        "debt_projection": "Проекция погашения долга",
        "reserve_projection": "Проекция резерва",
        "essentials_risk": "Покрытие обязательных расходов",
        "payoff_after_planned_date": "Погашение позже вашей плановой даты",
        "payoff_on_plan": "Погашение в пределах вашей плановой даты",
        "target_exceeded": "Расход выше вашей цели",
        "related": "связано",
        "temporally_associated": "совпало по времени",
        "co_occurs_with": "встречается вместе",
        "conflicts_with": "в напряжении с",
        "supports": "поддерживает",
        "preceded_by": "после",
        "followed_by": "до",
        "may_contribute_to": "может влиять на (гипотеза)",
        "may_increase_risk_of": "может повышать риск (гипотеза)",
        "may_reduce_probability_of": "может снижать вероятность (гипотеза)",
        "fixed_monthly_payment": "фиксированный ежемесячный платёж",
        "fixed_annual_rate": "фиксированная годовая ставка",
        "no_other_new_borrowing": "без других новых заимствований",
        "no_other_inflows_or_outflows": "прочие поступления и расходы не учтены",
        "reserves_summed_same_currency": "резервы суммированы (одна валюта)",
        "threshold_not_set_calculated_to_zero": "порог не задан — расчёт до нуля",
        "same_amount_each_time": "каждый раз та же сумма",
        "expectation_is_a_prediction_not_a_norm": "ожидание — прогноз, а не норма",
        "one_off_draw": "разовое списание",
        "income_not_modeled": "доход не моделируется",
        "currency_mismatch": "разные валюты — пересчёт не выполняется",
        "expense_may_already_be_in_outstanding": "сумма могла уже входить в остаток долга",
        "expense_may_already_be_in_reserve": "сумма могла уже быть учтена в резерве",
        "marked_one_off": "отмечено как разовое",
        "target_or_expectation": "цель или ожидание на месяц",
        "recurrence_per_month": "сколько раз в месяц",
        "expected_recurrence": "повторяемость",
        "obligation": "какой долг",
        "credit_portion": "доля кредита",
        "outstanding": "остаток долга",
        "monthly_payment": "ежемесячный платёж",
        "annual_rate_percent": "годовая ставка",
        "reserve": "резерв",
        "essentials": "обязательные расходы",
    },
    "uk": {
        "finance_spend_vs_expectation": "Витрати місяця та очікування",
        "finance_spend_vs_prior": "Витрати місяця та минулий місяць",
        "finance_expectation_revisions": "Перегляди очікування",
        "finance_target_state": "Витрати місяця та ціль",
        "project_forecast_revisions": "Перегляди прогнозу проєкту",
        "project_completion": "Завершення проєкту",
        "experiment_lifecycle": "Експеримент",
        "observation": "Спостереження",
        "budget_deviation": "Відхилення від бюджету",
        "repeat_scenario": "Якщо повториться",
        "debt_projection": "Проєкція погашення боргу",
        "reserve_projection": "Проєкція резерву",
        "essentials_risk": "Покриття обов'язкових витрат",
        "payoff_after_planned_date": "Погашення пізніше за вашу планову дату",
        "payoff_on_plan": "Погашення в межах вашої планової дати",
        "target_exceeded": "Витрати вищі за вашу ціль",
        "related": "пов'язано",
        "temporally_associated": "збіглося в часі",
        "co_occurs_with": "трапляється разом",
        "conflicts_with": "у напрузі з",
        "supports": "підтримує",
        "preceded_by": "після",
        "followed_by": "до",
        "may_contribute_to": "може впливати на (гіпотеза)",
        "may_increase_risk_of": "може підвищувати ризик (гіпотеза)",
        "may_reduce_probability_of": "може знижувати ймовірність (гіпотеза)",
        "fixed_monthly_payment": "фіксований щомісячний платіж",
        "fixed_annual_rate": "фіксована річна ставка",
        "no_other_new_borrowing": "без інших нових позик",
        "no_other_inflows_or_outflows": "інші надходження й витрати не враховано",
        "reserves_summed_same_currency": "резерви підсумовано (одна валюта)",
        "threshold_not_set_calculated_to_zero": "поріг не задано — розрахунок до нуля",
        "same_amount_each_time": "щоразу та сама сума",
        "expectation_is_a_prediction_not_a_norm": "очікування — прогноз, а не норма",
        "one_off_draw": "разове списання",
        "income_not_modeled": "дохід не моделюється",
        "currency_mismatch": "різні валюти — перерахунок не виконується",
        "expense_may_already_be_in_outstanding": "сума могла вже входити в залишок боргу",
        "expense_may_already_be_in_reserve": "сума могла вже бути врахована в резерві",
        "marked_one_off": "позначено як разове",
        "target_or_expectation": "ціль або очікування на місяць",
        "recurrence_per_month": "скільки разів на місяць",
        "expected_recurrence": "повторюваність",
        "obligation": "який борг",
        "credit_portion": "частка кредиту",
        "outstanding": "залишок боргу",
        "monthly_payment": "щомісячний платіж",
        "annual_rate_percent": "річна ставка",
        "reserve": "резерв",
        "essentials": "обов'язкові витрати",
    },
}


def labels(locale: str) -> dict[str, str]:
    return UK if locale == "uk" else RU


def term(locale: str, code: str | None) -> str:
    if code is None:
        return "—"
    return TERMS.get(locale, TERMS["ru"]).get(code, code)


# Consequence export vocabulary (values, result lines, context fields).
_CONSEQUENCE_TERMS: dict[str, dict[str, str]] = {
    "ru": {
        "payoff.does_not_decrease": "при этих допущениях долг не уменьшается",
        "payoff.beyond_horizon": "дольше 50 лет",
        "payoff.paid_off": "погашен",
        "res.over_target": "к вашей цели",
        "res.vs_expectation": "к ожиданию (не оценка)",
        "res.month_actual": "расход месяца",
        "res.target": "цель",
        "res.expectation": "ожидание",
        "res.expense_amount": "сумма расхода",
        "res.monthly": "в месяц",
        "res.twelve_months": "за 12 месяцев",
        "res.a_as_entered": "погашение как сейчас",
        "res.b_with_this_expense": "с этим расходом",
        "res.c_if_repeated": "если будет повторяться",
        "res.delta_days_b": "сдвиг из-за этого расхода",
        "res.delta_days_c": "сдвиг при повторении",
        "res.reserve": "резерв",
        "res.after_this_expense": "после расхода",
        "res.threshold": "порог",
        "res.monthly_draw": "списание в месяц",
        "res.months_until_threshold": "месяцев до порога",
        "res.coverage_months_now": "покрытие обязательных расходов сейчас, мес.",
        "res.coverage_months_after": "после списания, мес.",
        "res.draw": "списание",
        "unit.days": "дн.",
        "plan.planned": "запланировано",
        "plan.unplanned": "незапланировано",
        "plan.unknown": "запланированность неизвестна",
        "fund.unknown": "источник оплаты неизвестен",
        "fund.income": "из дохода",
        "fund.cash_balance": "наличные",
        "fund.debit_balance": "карта / счёт",
        "fund.credit": "кредит",
        "fund.borrowed": "в долг",
        "fund.mixed": "смешанно",
        "field.plannedness": "запланированность",
        "field.funding_source": "источник оплаты",
        "field.purpose": "на что",
        "field.motive": "зачем",
        "field.emotional_context": "состояние (ваша заметка)",
        "field.worth_it": "стоило того",
        "field.expected_recurrence": "повторяемость",
        "field.recurrence_per_month": "раз в месяц",
        "value.planned": "запланировано",
        "value.unplanned": "незапланировано",
        "value.unknown": "не знаю",
        "value.income": "из дохода",
        "value.cash_balance": "наличные",
        "value.debit_balance": "карта / счёт",
        "value.credit": "кредит",
        "value.borrowed": "в долг",
        "value.mixed": "смешанно",
        "value.yes": "да",
        "value.no": "нет",
        "value.unsure": "не уверен",
        "value.one_off": "разовое",
        "value.occasional": "иногда",
        "value.recurring": "регулярно",
        "funding_unknown": "источник оплаты не указан",
        "funding_income": "оплачено из дохода",
        "funding_cash_balance": "оплачено наличными",
        "funding_debit_balance": "оплачено с карты/счёта",
        "funding_credit": "оплачено кредитом",
        "funding_borrowed": "оплачено в долг",
        "funding_mixed": "смешанная оплата",
        "month_actual_insufficient_data": "расход месяца известен не полностью",
        "month_actual_no_data": "за месяц нет расходов",
        "as_of": "на дату",
        "essentials_monthly": "обязательные расходы в месяц"
    },
    "uk": {
        "payoff.does_not_decrease": "за цих припущень борг не зменшується",
        "payoff.beyond_horizon": "довше 50 років",
        "payoff.paid_off": "погашено",
        "res.over_target": "до вашої цілі",
        "res.vs_expectation": "до очікування (не оцінка)",
        "res.month_actual": "витрати місяця",
        "res.target": "ціль",
        "res.expectation": "очікування",
        "res.expense_amount": "сума витрати",
        "res.monthly": "на місяць",
        "res.twelve_months": "за 12 місяців",
        "res.a_as_entered": "погашення як зараз",
        "res.b_with_this_expense": "з цією витратою",
        "res.c_if_repeated": "якщо повторюватиметься",
        "res.delta_days_b": "зсув через цю витрату",
        "res.delta_days_c": "зсув при повторенні",
        "res.reserve": "резерв",
        "res.after_this_expense": "після витрати",
        "res.threshold": "поріг",
        "res.monthly_draw": "списання на місяць",
        "res.months_until_threshold": "місяців до порогу",
        "res.coverage_months_now": "покриття обов'язкових витрат зараз, міс.",
        "res.coverage_months_after": "після списання, міс.",
        "res.draw": "списання",
        "unit.days": "дн.",
        "plan.planned": "заплановано",
        "plan.unplanned": "незаплановано",
        "plan.unknown": "запланованість невідома",
        "fund.unknown": "джерело оплати невідоме",
        "fund.income": "з доходу",
        "fund.cash_balance": "готівка",
        "fund.debit_balance": "картка / рахунок",
        "fund.credit": "кредит",
        "fund.borrowed": "у борг",
        "fund.mixed": "змішано",
        "field.plannedness": "запланованість",
        "field.funding_source": "джерело оплати",
        "field.purpose": "на що",
        "field.motive": "навіщо",
        "field.emotional_context": "стан (ваша нотатка)",
        "field.worth_it": "чи було того варте",
        "field.expected_recurrence": "повторюваність",
        "field.recurrence_per_month": "разів на місяць",
        "value.planned": "заплановано",
        "value.unplanned": "незаплановано",
        "value.unknown": "не знаю",
        "value.income": "з доходу",
        "value.cash_balance": "готівка",
        "value.debit_balance": "картка / рахунок",
        "value.credit": "кредит",
        "value.borrowed": "у борг",
        "value.mixed": "змішано",
        "value.yes": "так",
        "value.no": "ні",
        "value.unsure": "не впевнений",
        "value.one_off": "разове",
        "value.occasional": "іноді",
        "value.recurring": "регулярно",
        "funding_unknown": "джерело оплати не вказано",
        "funding_income": "оплачено з доходу",
        "funding_cash_balance": "оплачено готівкою",
        "funding_debit_balance": "оплачено з картки/рахунку",
        "funding_credit": "оплачено кредитом",
        "funding_borrowed": "оплачено в борг",
        "funding_mixed": "змішана оплата",
        "month_actual_insufficient_data": "витрати місяця відомі не повністю",
        "month_actual_no_data": "за місяць немає витрат",
        "as_of": "на дату",
        "essentials_monthly": "обов'язкові витрати на місяць"
    }
}
_CONSEQUENCE_TERMS["ru"].update({"expense_amount": "сумма расхода", "month_actual": "расход месяца",
                                  "target": "цель", "expectation": "ожидание"})
_CONSEQUENCE_TERMS["uk"].update({"expense_amount": "сума витрати", "month_actual": "витрати місяця",
                                  "target": "ціль", "expectation": "очікування"})
for _locale, _terms in _CONSEQUENCE_TERMS.items():
    TERMS[_locale].update(_terms)
